/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EsperaRouteImport } from './routes/espera'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuiosqueRouteImport } from './routes/quiosque'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrgDashboardRouteImport } from './routes/_authenticated/org.dashboard'
import { Route as AuthenticatedOrgGabineteRouteImport } from './routes/_authenticated/org.gabinete'
import { Route as AuthenticatedOrgRecepcaoRouteImport } from './routes/_authenticated/org.recepcao'
import { Route as AuthenticatedOrgTurnoRouteImport } from './routes/_authenticated/org.turno'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperaRoute = EsperaRouteImport.update({
  id: '/espera',
  path: '/espera',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiosqueRoute = QuiosqueRouteImport.update({
  id: '/quiosque',
  path: '/quiosque',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgDashboardRoute =
  AuthenticatedOrgDashboardRouteImport.update({
    id: '/org/dashboard',
    path: '/org/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgGabineteRoute =
  AuthenticatedOrgGabineteRouteImport.update({
    id: '/org/gabinete',
    path: '/org/gabinete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgRecepcaoRoute =
  AuthenticatedOrgRecepcaoRouteImport.update({
    id: '/org/recepcao',
    path: '/org/recepcao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgTurnoRoute = AuthenticatedOrgTurnoRouteImport.update({
  id: '/org/turno',
  path: '/org/turno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/espera': typeof EsperaRoute
  '/login': typeof LoginRoute
  '/quiosque': typeof QuiosqueRoute
  '/tv': typeof TvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/org/gabinete': typeof AuthenticatedOrgGabineteRoute
  '/org/recepcao': typeof AuthenticatedOrgRecepcaoRoute
  '/org/turno': typeof AuthenticatedOrgTurnoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/espera': typeof EsperaRoute
  '/login': typeof LoginRoute
  '/quiosque': typeof QuiosqueRoute
  '/tv': typeof TvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/org/gabinete': typeof AuthenticatedOrgGabineteRoute
  '/org/recepcao': typeof AuthenticatedOrgRecepcaoRoute
  '/org/turno': typeof AuthenticatedOrgTurnoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/espera': typeof EsperaRoute
  '/login': typeof LoginRoute
  '/quiosque': typeof QuiosqueRoute
  '/tv': typeof TvRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/_authenticated/org/gabinete': typeof AuthenticatedOrgGabineteRoute
  '/_authenticated/org/recepcao': typeof AuthenticatedOrgRecepcaoRoute
  '/_authenticated/org/turno': typeof AuthenticatedOrgTurnoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espera'
    | '/login'
    | '/quiosque'
    | '/tv'
    | '/admin'
    | '/org/dashboard'
    | '/org/gabinete'
    | '/org/recepcao'
    | '/org/turno'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/espera'
    | '/login'
    | '/quiosque'
    | '/tv'
    | '/admin'
    | '/org/dashboard'
    | '/org/gabinete'
    | '/org/recepcao'
    | '/org/turno'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/espera'
    | '/login'
    | '/quiosque'
    | '/tv'
    | '/_authenticated/admin'
    | '/_authenticated/org/dashboard'
    | '/_authenticated/org/gabinete'
    | '/_authenticated/org/recepcao'
    | '/_authenticated/org/turno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EsperaRoute: typeof EsperaRoute
  LoginRoute: typeof LoginRoute
  QuiosqueRoute: typeof QuiosqueRoute
  TvRoute: typeof TvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espera': {
      id: '/espera'
      path: '/espera'
      fullPath: '/espera'
      preLoaderRoute: typeof EsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiosque': {
      id: '/quiosque'
      path: '/quiosque'
      fullPath: '/quiosque'
      preLoaderRoute: typeof QuiosqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/dashboard': {
      id: '/_authenticated/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/gabinete': {
      id: '/_authenticated/org/gabinete'
      path: '/org/gabinete'
      fullPath: '/org/gabinete'
      preLoaderRoute: typeof AuthenticatedOrgGabineteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/recepcao': {
      id: '/_authenticated/org/recepcao'
      path: '/org/recepcao'
      fullPath: '/org/recepcao'
      preLoaderRoute: typeof AuthenticatedOrgRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/turno': {
      id: '/_authenticated/org/turno'
      path: '/org/turno'
      fullPath: '/org/turno'
      preLoaderRoute: typeof AuthenticatedOrgTurnoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedOrgDashboardRoute: typeof AuthenticatedOrgDashboardRoute
  AuthenticatedOrgGabineteRoute: typeof AuthenticatedOrgGabineteRoute
  AuthenticatedOrgRecepcaoRoute: typeof AuthenticatedOrgRecepcaoRoute
  AuthenticatedOrgTurnoRoute: typeof AuthenticatedOrgTurnoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedOrgDashboardRoute: AuthenticatedOrgDashboardRoute,
  AuthenticatedOrgGabineteRoute: AuthenticatedOrgGabineteRoute,
  AuthenticatedOrgRecepcaoRoute: AuthenticatedOrgRecepcaoRoute,
  AuthenticatedOrgTurnoRoute: AuthenticatedOrgTurnoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EsperaRoute: EsperaRoute,
  LoginRoute: LoginRoute,
  QuiosqueRoute: QuiosqueRoute,
  TvRoute: TvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
